version: '3'
services:
  api:
    container_name: api
    build: ./blog
    volumes:
      - "./blog:/var/lib/app"
    depends_on:
      - db
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      POSGRE_USER: $POSGRE_USER
      POSGRE_PASSWORD: $POSGRE_PASSWORD
      POSGRE_HOST: $POSGRE_HOST
      POSGRE_PORT: $POSGRE_PORT
      POSGRE_DATABASE: $POSGRE_DATABASE
  db:
    build: ./db
    container_name: mypg
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: $POSGRE_USER
      POSTGRES_PASSWORD: $POSGRE_PASSWOR
      POSTGRES_DB: $POSGRE_DATABASE
